name: music_library_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  just_audio: ^0.9.40  # Для воспроизведения аудио

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true